from __future__ import annotations

import asyncio
import json
import re
from datetime import datetime
from pathlib import Path

from core.orchestrator.rollback import rollback_engine
from core.self.manifest import GENERATED_UI_DIR, self_manifest
from core.shadow.channel import shadow_channel

ALLOWED_CSS_PROPS = {
    "color",
    "background",
    "background-color",
    "border",
    "border-color",
    "border-radius",
    "padding",
    "margin",
    "font-size",
    "font-weight",
    "letter-spacing",
    "gap",
    "grid-template-columns",
    "display",
    "flex-direction",
    "align-items",
    "justify-content",
    "width",
    "height",
    "max-width",
    "opacity",
    "transition",
    "overflow",
}


def _is_inside(path: Path, base_dir: Path) -> bool:
    try:
        path.resolve().relative_to(base_dir.resolve())
        return True
    except Exception:
        return False


class UIMutationEngine:
    async def generate_panel(
        self,
        panel_name: str,
        description: str,
        mission_id: str,
    ) -> dict:
        if not re.match(r"^[A-Za-z][A-Za-z0-9]+$", panel_name):
            return {"success": False, "error": "Invalid panel name"}

        checkpoint = await rollback_engine.create_checkpoint(
            mission_id,
            {"action": "generate_panel", "panel_name": panel_name},
        )

        tsx = self._build_panel_tsx(panel_name, description)
        path = GENERATED_UI_DIR / f"{panel_name}.tsx"
        if not _is_inside(path, GENERATED_UI_DIR):
            return {"success": False, "error": "Invalid target path"}

        try:
            loop = asyncio.get_event_loop()
            await loop.run_in_executor(
                None,
                path.write_text,
                tsx,
                "utf-8",
            )
            await loop.run_in_executor(
                None, self_manifest.register_panel, panel_name, str(path)
            )

            await shadow_channel.log(
                "ui_panel_generated",
                mission_id,
                {"panel_name": panel_name, "path": str(path)},
            )
            return {
                "success": True,
                "panel_name": panel_name,
                "path": str(path),
                "preview": tsx[:200] + "...",
            }
        except Exception as exc:
            await rollback_engine.rollback_to(checkpoint)
            return {"success": False, "error": str(exc)}

    async def apply_style_patch(
        self,
        target_css_prop: str,
        new_value: str,
        selector: str,
        mission_id: str,
    ) -> dict:
        if target_css_prop not in ALLOWED_CSS_PROPS:
            return {
                "success": False,
                "error": f"CSS property '{target_css_prop}' not in allowlist",
            }

        checkpoint = await rollback_engine.create_checkpoint(
            mission_id,
            {
                "action": "style_patch",
                "selector": selector,
                "property": target_css_prop,
                "value": new_value,
            },
        )

        patch_file = GENERATED_UI_DIR / "style_patches.json"
        if not _is_inside(patch_file, GENERATED_UI_DIR):
            return {"success": False, "error": "Invalid patch target"}

        loop = asyncio.get_event_loop()
        try:
            existing: dict[str, dict[str, str]] = {}
            if patch_file.exists():
                text = await loop.run_in_executor(None, patch_file.read_text, "utf-8")
                existing = json.loads(text) if text.strip() else {}

            existing.setdefault(selector, {})[target_css_prop] = new_value
            await loop.run_in_executor(
                None,
                patch_file.write_text,
                json.dumps(existing, indent=2),
                "utf-8",
            )

            await shadow_channel.log(
                "style_patch_applied",
                mission_id,
                {
                    "selector": selector,
                    "property": target_css_prop,
                    "value": new_value,
                },
            )
            return {"success": True, "patches": existing}
        except Exception as exc:
            await rollback_engine.rollback_to(checkpoint)
            return {"success": False, "error": str(exc)}

    def _build_panel_tsx(self, name: str, description: str) -> str:
        return f'''import {{ useEffect, useState }} from "preact/hooks"

// AUTO-GENERATED BY NEXUSMON SELF-MODIFICATION ENGINE
// Generated: {datetime.utcnow().isoformat()}
// Description: {description}
// Do not edit manually - managed by NEXUSMON

export function {name}() {{
  const [data, setData] = useState<any>(null)

  useEffect(() => {{
    // Panel initialized - wire to /api/* endpoint as needed.
    setData(null)
  }}, [])

  return (
    <div class="panel">
      <div class="panel-header">
        <span style={{{{ color: "#9b59b6" }}}}>{name.upper()}</span>
        <span style={{{{ color: "#444", fontSize: 10 }}}}>GENERATED</span>
      </div>
      <div class="muted">
        {description}
      </div>
      <div class="muted">state: {{String(Boolean(data))}}</div>
    </div>
  )
}}
'''


ui_mutation_engine = UIMutationEngine()
