from __future__ import annotations

import asyncio
import re
from datetime import datetime
from pathlib import Path

from core.orchestrator.rollback import rollback_engine
from core.self.manifest import GENERATED_WORKER_DIR, self_manifest
from core.shadow.channel import shadow_channel


def _is_inside(path: Path, base_dir: Path) -> bool:
    try:
        path.resolve().relative_to(base_dir.resolve())
        return True
    except Exception:
        return False


class WorkerForge:
    async def forge_worker(
        self,
        worker_name: str,
        worker_role: str,
        system_prefix: str,
        mission_id: str,
        activate: bool = False,
    ) -> dict:
        if not re.match(r"^[A-Z][A-Z0-9_]+$", worker_name):
            return {
                "success": False,
                "error": "Worker name must be uppercase alphanumeric with underscores",
            }

        checkpoint = await rollback_engine.create_checkpoint(
            mission_id,
            {
                "action": "forge_worker",
                "worker_name": worker_name,
                "activate": activate,
            },
        )

        py = self._build_worker_py(worker_name, worker_role, system_prefix)
        path = GENERATED_WORKER_DIR / f"{worker_name.lower()}_worker.py"
        if not _is_inside(path, GENERATED_WORKER_DIR):
            return {"success": False, "error": "Invalid target path"}

        try:
            loop = asyncio.get_event_loop()
            await loop.run_in_executor(
                None,
                path.write_text,
                py,
                "utf-8",
            )
            await loop.run_in_executor(
                None,
                self_manifest.register_worker,
                worker_name,
                str(path),
                activate,
            )

            await shadow_channel.log(
                "worker_forged",
                mission_id,
                {
                    "worker_name": worker_name,
                    "worker_role": worker_role,
                    "path": str(path),
                    "activate": activate,
                },
            )
            return {
                "success": True,
                "worker_name": worker_name,
                "path": str(path),
                "active": activate,
                "preview": py[:300] + "...",
            }
        except Exception as exc:
            await rollback_engine.rollback_to(checkpoint)
            return {"success": False, "error": str(exc)}

    async def activate_worker(self, worker_name: str, mission_id: str) -> dict:
        checkpoint = await rollback_engine.create_checkpoint(
            mission_id,
            {"action": "activate_worker", "worker_name": worker_name},
        )

        manifest_data = self_manifest.get_all()
        workers = manifest_data.get("generated_workers", [])
        match = next((worker for worker in workers if worker["name"] == worker_name), None)
        if not match:
            return {"success": False, "error": "Worker not found in manifest"}

        try:
            loop = asyncio.get_event_loop()
            await loop.run_in_executor(None, self_manifest.activate_worker, worker_name)
            await shadow_channel.log(
                "worker_activated",
                mission_id,
                {"worker_name": worker_name},
            )
            return {"success": True, "worker_name": worker_name, "active": True}
        except Exception as exc:
            await rollback_engine.rollback_to(checkpoint)
            return {"success": False, "error": str(exc)}

    def _build_worker_py(
        self,
        name: str,
        role: str,
        system_prefix: str,
    ) -> str:
        class_name = f"{name.title().replace('_', '')}Worker"
        return f'''from __future__ import annotations
from typing import Any

from core.models.mission import Mission
from core.orchestrator.worker_router import BaseWorker

# AUTO-GENERATED BY NEXUSMON WORKER FORGE
# Generated: {datetime.utcnow().isoformat()}
# Worker:    {name}
# Role:      {role}
# Managed by NEXUSMON - activate via operator command.


class {class_name}(BaseWorker):
    """
    {role}
    Auto-generated worker. Requires operator activation.
    """

    name = "{name}"

    async def execute(self, mission: Mission) -> dict[str, Any]:
        from swarmz_runtime.bridge import call_v2

        prompt = mission.payload.get("prompt", "")
        response = await call_v2(
            prompt=f"[{system_prefix}]\\n{{prompt}}",
            tier=1,
            budget_tokens=mission.budget.tokens,
        )
        return {{
            "worker": self.name,
            "response": response.content,
            "tokens_used": response.tokens_used,
            "model": response.model_used,
            "latency_ms": response.latency_ms,
        }}
'''


worker_forge = WorkerForge()
